version: '3.0'
services:
  nodered:
    image: nodered/node-red-docker:latest
    hostname: nodered
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
      - "80:1880"
      - "9999:9999"
      - "8081:8081"
    depends_on:
      - "rabbitmq"
    volumes:
      - node-red:/data
  nodered2:
    image: nodered/node-red:latest
    hostname: nodered2
    container_name: nodered2
    restart: always
    ports:
      - "1881:1880"
    depends_on:
      - "rabbitmq"
    volumes:
      - node-red2:/data
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=mypassword 
      - INFLUXDB_USER=user 
      - INFLUXDB_USER_PASSWORD=mypassword
    hostname: influxdb
    restart: always
    container_name: influxdb
    volumes:
      - "/home/ubuntu/influxdata:/var/lib/influxdb"
  grafana:
    image: grafana/grafana:5.0.4
    container_name: grafana
    hostname: grafana
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=secret
  vernemq1:
    image: erlio/docker-vernemq
    container_name: vernemq1
    hostname: vernemq1
    restart: always
    ports:
      - "1883:1883"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "8080:15672"
      - "5672:5672"
  grafana2:
    image: grafana/grafana:latest
    container_name: grafana2
    hostname: grafana2
    volumes:
      - grafana2:/var/lib/grafana
    ports:
      - "3001:3000"
    user: "104"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

volumes:
  node-red:
  grafana2:
  node-red2:
