version: '3.0'
services:
  chronograf:
    image: chronograf
    hostname: chronograf
    container_name: chronograf
    ports:
      - "8888:8888"
    networks:
      - iotserver_net
    volumes:
      - chronograf:/var/lib/chronograf
  nodered:
    image: nodered/node-red-docker:latest
    hostname: nodered
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"
    networks:
      - iotserver_net
    depends_on:
      - "rabbitmq"
    volumes:
      - node-red:/data
  nodered2:
    image: nodered/node-red:latest
    hostname: nodered2
    container_name: nodered2
    ports:
      - "1881:1880"    
    networks:
      - iotserver_net
    depends_on:
      - "rabbitmq"
    volumes:
      - node-red2:/data
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=mypassword 
      - INFLUXDB_USER=user 
      - INFLUXDB_USER_PASSWORD=mypassword
    hostname: influxdb
    restart: always
    container_name: influxdb
    networks:
      - iotserver_net
    volumes:
      - "/home/ubuntu/influxdata:/var/lib/influxdb"
  kapacitor:
    image: kapacitor
    volumes:
      - "/home/ubuntu/kapacitor:/var/lib/kapacitor"
    links:
      - influxdb
    ports:
      - "9092:9092"
    networks:
      - iotserver_net
  grafana:
    image: grafana/grafana:5.0.4
    container_name: grafana
    hostname: grafana
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    networks:
      - iotserver_net
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=secret
  vernemq1:
    image: erlio/docker-vernemq
    container_name: vernemq1
    hostname: vernemq1
    restart: always
    ports:
      - "1883:1883"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
    networks: 
      iotserver_net: 
        ipv4_address: 172.28.1.100
  vernemq2:
    image: erlio/docker-vernemq
    container_name: vernemq2
    hostname: vernemq2
    restart: always
    ports:
      - "1884:1883"
    depends_on:
      - "vernemq1"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_DISCOVERY_NODE=172.28.1.100
    networks: 
      iotserver_net: 
        ipv4_address: 172.28.1.101 
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    networks:
      - iotserver_net
    ports:
      - "8080:15672"
      - "5672:5672"
  grafana2:
    image: grafana/grafana:latest
    container_name: grafana2
    hostname: grafana2
    volumes:
      - grafana2:/var/lib/grafana
    ports:
      - "3001:3000"
    user: "104"
    networks:
      - iotserver_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret

volumes:
  node-red:
  grafana2:
  node-red2:
  chronograf:

networks:
    iotserver_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
